@extends('layouts.app')
@section('page-title-html') Consortium <em>Registrations</em> @endsection
@section('page-subtitle') Candidate registrations submitted from consortiumstaffing.ca @endsection
@section('content')
@if(session('success'))
<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[12px] font-semibold text-emerald-700">{{ session('success') }}</div>
@endif
<div class="rounded-2xl border border-[#E8E6E1] bg-white shadow-sm overflow-hidden"><div class="flex items-center justify-between border-b border-[#EEECE8] px-5 py-4"><div><h2 class="text-[15px] font-bold text-[#1A1E2E]">Registration Submissions</h2><p class="text-[11px] text-[#8892A0]">{{ $unreviewedCount }} awaiting review</p></div><div class="flex items-center gap-2">@if(request()->hasAny(['month','year','gender','city','job_type','available_weekends','night_shifts']))<a href="{{ route('admin.consortium-registrations.index') }}" class="rounded-lg border border-[#DDE2EA] bg-white px-3 py-1.5 text-[10.5px] font-bold text-[#5A6478] hover:bg-[#F1F3F7]">Reset Filters</a>@endif<span class="rounded-full bg-blue-50 px-3 py-1 text-[11px] font-bold text-blue-600">{{ $registrations->total() }} total</span></div></div>
@include('admin.consortium-registrations.partials.filters')<div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-[#F8F9FB] text-[10px] uppercase tracking-wider text-[#8892A0]"><tr><th class="px-5 py-3">Candidate</th><th class="px-5 py-3">Contact</th><th class="px-5 py-3">City</th><th class="px-5 py-3">Eligibility</th><th class="px-5 py-3">Submitted</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody>
@forelse($registrations as $registration)<tr class="border-t border-[#F0EEE9] hover:bg-[#FBFCFE]"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-[12px] font-bold text-blue-600">{{ strtoupper(substr($registration->first_name,0,1).substr($registration->last_name,0,1)) }}</span><div><a href="{{ route('admin.consortium-registrations.show', array_merge(['registration' => $registration->id], request()->query())) }}" class="text-[13px] font-semibold text-[#1A1E2E] transition hover:text-[#2563EB] hover:underline">{{ $registration->first_name }} {{ $registration->last_name }}</a>@if(!$registration->reviewed_at)<span class="text-[9px] font-bold uppercase text-orange-500">New</span>@endif</div></div></td><td class="px-5 py-4 text-[12px] text-[#5A6478]">{{ $registration->email }}<br>{{ $registration->phone }}</td><td class="px-5 py-4 text-[12px] text-[#5A6478]">{{ $registration->city }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-[10px] font-bold {{ $registration->eligible_to_work_canada ? 'bg-emerald-50 text-emerald-600' : 'bg-red-50 text-red-600' }}">{{ $registration->eligible_to_work_canada ? 'Eligible' : 'Not eligible' }}</span></td><td class="px-5 py-4 text-[11px] text-[#8892A0]">{{ $registration->created_at->timezone($global->timezone)->format('M j, Y g:i A') }}</td><td class="px-5 py-4"><div class="flex items-center justify-end gap-2"><a href="{{ route('admin.consortium-registrations.show', array_merge(['registration' => $registration->id], request()->query())) }}" class="rounded-lg bg-blue-50 px-3 py-2 text-[11px] font-bold text-blue-600 hover:bg-blue-100">View Details</a>@if(auth()->user()->hasRole('admin'))<form method="POST" action="{{ route('admin.consortium-registrations.destroy',$registration) }}" onsubmit="return confirm('Move this registration to Trash?')">@csrf @method('DELETE')<button type="submit" class="rounded-lg border border-red-200 bg-white px-3 py-2 text-[11px] font-bold text-red-600 hover:bg-red-50"><i class="fa fa-trash-o"></i> Delete</button></form>@endif</div></td></tr>
@empty<tr><td colspan="6" class="px-5 py-16 text-center text-sm text-[#8892A0]">No registrations received yet.</td></tr>@endforelse
</tbody></table></div><div class="border-t border-[#EEECE8] px-5 py-4">{{ $registrations->links() }}</div></div>
@endsection
