@extends('layouts.app')
@section('page-title-html') Consortium <em>Registrations</em> @endsection
@section('page-subtitle') Candidate registrations submitted from consortiumstaffing.ca @endsection
@section('content')
<div class="rounded-2xl border border-[#E8E6E1] bg-white shadow-sm overflow-hidden"><div class="flex items-center justify-between border-b border-[#EEECE8] px-5 py-4"><div><h2 class="text-[15px] font-bold text-[#1A1E2E]">Registration Submissions</h2><p class="text-[11px] text-[#8892A0]">{{ $unreviewedCount }} awaiting review</p></div><div class="flex items-center gap-2">@if(request()->hasAny(['month','year','gender','city','job_type','available_weekends','night_shifts']))<a href="{{ route('admin.consortium-registrations.index') }}" class="rounded-lg border border-[#DDE2EA] bg-white px-3 py-1.5 text-[10.5px] font-bold text-[#5A6478] hover:bg-[#F1F3F7]">Reset Filters</a>@endif<span class="rounded-full bg-blue-50 px-3 py-1 text-[11px] font-bold text-blue-600">{{ $registrations->total() }} total</span></div></div>
<form id="consortium-registration-filters" method="GET" action="{{ route('admin.consortium-registrations.index') }}" class="border-b border-[#EEECE8] bg-[#FBFCFE] px-5 py-4">
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">
        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">Submitted Month</label><select name="month" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All Months</option>@foreach($filterMonths as $month)<option value="{{ $month }}" @selected((int) request('month') === (int) $month)>{{ \Carbon\Carbon::create()->month($month)->format('F') }}</option>@endforeach</select></div>
        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">Submitted Year</label><select name="year" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All Years</option>@foreach($filterYears as $year)<option value="{{ $year }}" @selected((string) request('year') === (string) $year)>{{ $year }}</option>@endforeach</select></div>
        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">Gender</label><select name="gender" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All Genders</option>@foreach($filterGenders as $gender)<option value="{{ $gender }}" @selected(request('gender') === $gender)>{{ $gender }}</option>@endforeach</select></div>
        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">City</label><select name="city" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All Cities</option>@foreach($filterCities as $city)<option value="{{ $city }}" @selected(request('city') === $city)>{{ $city }}</option>@endforeach</select></div>
        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">Job Type</label><select name="job_type" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All Job Types</option>@foreach($filterJobTypes as $jobType)<option value="{{ $jobType }}" @selected(request('job_type') === $jobType)>{{ $jobType }}</option>@endforeach</select></div>        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">Available Weekends</label><select name="available_weekends" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All</option><option value="1" @selected(request('available_weekends') === '1')>Yes</option><option value="0" @selected(request('available_weekends') === '0')>No</option></select></div>
        <div><label class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-[#8892A0]">Night Shifts</label><select name="night_shifts" class="registration-auto-filter w-full rounded-xl border border-[#DDE2EA] bg-white px-3 py-2.5 text-[12px] text-[#3D4A5C] outline-none focus:border-blue-500"><option value="">All</option><option value="1" @selected(request('night_shifts') === '1')>Yes</option><option value="0" @selected(request('night_shifts') === '0')>No</option></select></div>
        
    </div>
</form><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-[#F8F9FB] text-[10px] uppercase tracking-wider text-[#8892A0]"><tr><th class="px-5 py-3">Candidate</th><th class="px-5 py-3">Contact</th><th class="px-5 py-3">City</th><th class="px-5 py-3">Eligibility</th><th class="px-5 py-3">Submitted</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody>
@forelse($registrations as $registration)<tr class="border-t border-[#F0EEE9] hover:bg-[#FBFCFE]"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-[12px] font-bold text-blue-600">{{ strtoupper(substr($registration->first_name,0,1).substr($registration->last_name,0,1)) }}</span><div><a href="{{ route('admin.consortium-registrations.show', $registration) }}" class="text-[13px] font-semibold text-[#1A1E2E] transition hover:text-[#2563EB] hover:underline">{{ $registration->first_name }} {{ $registration->last_name }}</a>@if(!$registration->reviewed_at)<span class="text-[9px] font-bold uppercase text-orange-500">New</span>@endif</div></div></td><td class="px-5 py-4 text-[12px] text-[#5A6478]">{{ $registration->email }}<br>{{ $registration->phone }}</td><td class="px-5 py-4 text-[12px] text-[#5A6478]">{{ $registration->city }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-[10px] font-bold {{ $registration->eligible_to_work_canada ? 'bg-emerald-50 text-emerald-600' : 'bg-red-50 text-red-600' }}">{{ $registration->eligible_to_work_canada ? 'Eligible' : 'Not eligible' }}</span></td><td class="px-5 py-4 text-[11px] text-[#8892A0]">{{ $registration->created_at->timezone($global->timezone)->format('M j, Y g:i A') }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.consortium-registrations.show',$registration) }}" class="rounded-lg bg-blue-50 px-3 py-2 text-[11px] font-bold text-blue-600 hover:bg-blue-100">View Details</a></td></tr>
@empty<tr><td colspan="6" class="px-5 py-16 text-center text-sm text-[#8892A0]">No registrations received yet.</td></tr>@endforelse
</tbody></table></div><div class="border-t border-[#EEECE8] px-5 py-4">{{ $registrations->links() }}</div></div>
@endsection

@push('footer-script')
<script>
$(document).on('change', '.registration-auto-filter', function () {
    $('#consortium-registration-filters').trigger('submit');
});
</script>
@endpush