@extends('layouts.app')
@section('page-title-html') Registration <em>Details</em> @endsection
@section('page-subtitle') {{ $registration->first_name }} {{ $registration->last_name }} @endsection
@section('create-button')<a href="{{ route('admin.consortium-registrations.index') }}" class="rounded-xl border border-[#DDE2EA] bg-white px-4 py-2 text-[12px] font-semibold text-[#5A6478]">Back to Registrations</a>@endsection
@section('content')
@php $rows=['Email'=>$registration->email,'Phone'=>$registration->phone,'Gender'=>$registration->gender,'Date of Birth'=>$registration->date_of_birth?->format('M j, Y'),'Street Address'=>$registration->street_address,'City'=>$registration->city,'Eligible to Work in Canada'=>$registration->eligible_to_work_canada?'Yes':'No','Status in Canada'=>$registration->status_in_canada,'Preferred Job Type'=>$registration->preferred_job_type,'Mode of Commute'=>$registration->commute_mode,'Years of Experience'=>$registration->years_experience,'Original Experience Response'=>$registration->legacy_experience_text,'Industry / Expertise'=>$registration->industry_expertise,'Available Weekends'=>$registration->available_weekends?'Yes':'No','Available Night Shifts'=>$registration->available_night_shifts?'Yes':'No','Referral Source'=>$registration->referral_source,'SMS Consent'=>$registration->sms_consent?'Yes':'No']; @endphp
<div class="mx-auto max-w-5xl space-y-4"><div class="rounded-2xl border border-[#E8E6E1] bg-white p-6 shadow-sm"><div class="flex items-center gap-4"><span class="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-lg font-bold text-blue-600">{{ strtoupper(substr($registration->first_name,0,1).substr($registration->last_name,0,1)) }}</span><div><h2 class="text-xl font-bold text-[#1A1E2E]">{{ $registration->first_name }} {{ $registration->last_name }}</h2><p class="text-xs text-[#8892A0]">Submitted {{ $registration->created_at->timezone($global->timezone)->format('M j, Y g:i A') }}</p></div>@if($registration->resume_file)<a href="{{ route('admin.consortium-registrations.resume',$registration) }}" class="ml-auto rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white">Download Resume</a>@endif</div></div>
<div class="grid grid-cols-1 gap-4 md:grid-cols-2">@foreach($rows as $label=>$value)<div class="rounded-xl border border-[#E8E6E1] bg-white px-4 py-3"><p class="text-[10px] font-bold uppercase tracking-wider text-[#9AA4B2]">{{ $label }}</p><p class="mt-1 text-[13px] font-medium text-[#334155]">{{ $value ?: '—' }}</p></div>@endforeach</div>
<div class="rounded-2xl border border-[#E8E6E1] bg-white p-5"><p class="text-[10px] font-bold uppercase tracking-wider text-[#9AA4B2]">Additional Information</p><p class="mt-2 whitespace-pre-wrap text-[13px] leading-6 text-[#334155]">{{ $registration->additional_information ?: 'No additional information provided.' }}</p></div></div>
@endsection